#!/bin/sh -ex
make distclean

mpicxx -std=c++17 -O2 -Wall -fPIC -pthread -m64 -I/usr/include/root -I../include -c -o probmain.o probmain.cc
mpicxx -std=c++17 -O2 -Wall -fPIC -pthread -m64 -I/usr/include/root -I../include -c -o probmain_mpi.o probmain_mpi.cc
mpicxx -std=c++17 -O2 -Wall -fPIC -pthread -m64 -I/usr/local/include/coin-or -I../include -I/usr/include/root -c -o TMinLkhd.o TMinLkhd.cc
mpicxx -std=c++17 -O2 -Wall -fPIC -pthread -m64 -I/usr/local/include/coin-or -I../include -I/usr/include/root -c -o minlkhd_nlp.o minlkhd_nlp.cc
mpicxx -std=c++17 -O2 -Wall -fPIC -pthread -m64 -I../include -I/usr/include/root -c -o TModel.o TModel.cc
mpicxx -std=c++17 -O2 -Wall -fPIC -pthread -m64 -c -o gaushermite.o gaushermite.C
mpicxx -std=c++17 -O2 -Wall -fPIC -pthread -m64 -I/usr/include/root -c -o BitFunc.o BitFunc.cc
