/********************************************************************
* TMinLkhdCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TMinLkhdCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTMinLkhdCint();
extern void G__cpp_setup_inheritanceTMinLkhdCint();
extern void G__cpp_setup_typetableTMinLkhdCint();
extern void G__cpp_setup_memvarTMinLkhdCint();
extern void G__cpp_setup_globalTMinLkhdCint();
extern void G__cpp_setup_memfuncTMinLkhdCint();
extern void G__cpp_setup_funcTMinLkhdCint();
extern void G__set_cpp_environmentTMinLkhdCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/opt/knitro-6.0.1-z/include/knitro.h"
#include "TMinLkhd.cc"
#include "TModel.cc"
#include "gaushermite.C"
#include "BitFunc.cc"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TMinLkhdCintLN_TClass;
extern G__linked_taginfo G__TMinLkhdCintLN_TBuffer;
extern G__linked_taginfo G__TMinLkhdCintLN_TMemberInspector;
extern G__linked_taginfo G__TMinLkhdCintLN_TObject;
extern G__linked_taginfo G__TMinLkhdCintLN_TNamed;
extern G__linked_taginfo G__TMinLkhdCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TMinLkhdCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TMinLkhdCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TMinLkhdCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TString;
extern G__linked_taginfo G__TMinLkhdCintLN_TModel;
extern G__linked_taginfo G__TMinLkhdCintLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TMinLkhdCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMinLkhdCintLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TMinLkhdCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMinLkhd;
extern G__linked_taginfo G__TMinLkhdCintLN_vectorlETModelcOallocatorlETModelgRsPgR;
extern G__linked_taginfo G__TMinLkhdCintLN_reverse_iteratorlEvectorlETModelcOallocatorlETModelgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMinLkhdCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TMinLkhdCintLN_TMatrixTSparseDiaglEfloatgR;

/* STUB derived class for protected member access */
