# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Gauss-Hermite quadrature nodes and weights
#'
#' @param n Number of quadrature points
#' @return List with nodes and weights
#' @export
gauss_hermite_quadrature <- function(n) {
    .Call('_factorana_gauss_hermite_quadrature', PACKAGE = 'factorana', n)
}

#' Initialize a FactorModel C++ object from R model system
#'
#' @param model_system R model_system object
#' @param data Data frame or matrix with all variables
#' @param n_quad Number of quadrature points
#' @return External pointer to FactorModel object
#' @export
initialize_factor_model_cpp <- function(model_system, data, n_quad = 8L) {
    .Call('_factorana_initialize_factor_model_cpp', PACKAGE = 'factorana', model_system, data, n_quad)
}

#' Evaluate log-likelihood for given parameters
#'
#' @param fm_ptr External pointer to FactorModel object
#' @param params Vector of parameters
#' @param compute_gradient Whether to compute gradient (default FALSE)
#' @param compute_hessian Whether to compute Hessian (default FALSE)
#' @return List with log-likelihood, gradient (if requested), and Hessian (if requested)
#' @export
evaluate_likelihood_cpp <- function(fm_ptr, params, compute_gradient = FALSE, compute_hessian = FALSE) {
    .Call('_factorana_evaluate_likelihood_cpp', PACKAGE = 'factorana', fm_ptr, params, compute_gradient, compute_hessian)
}

#' Evaluate log-likelihood only (for optimization)
#'
#' @param fm_ptr External pointer to FactorModel object
#' @param params Vector of parameters
#' @return Log-likelihood value
#' @export
evaluate_loglik_only_cpp <- function(fm_ptr, params) {
    .Call('_factorana_evaluate_loglik_only_cpp', PACKAGE = 'factorana', fm_ptr, params)
}

#' Get parameter counts from FactorModel
#'
#' @param fm_ptr External pointer to FactorModel object
#' @return List with parameter count information
#' @export
get_parameter_info_cpp <- function(fm_ptr) {
    .Call('_factorana_get_parameter_info_cpp', PACKAGE = 'factorana', fm_ptr)
}

